=== samirichards/CM-Assistant/CM Assistant_UWP/CM Assistant_UWP/Data/BracketsSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="XMLSchema1"
    targetNamespace="http://tempuri.org/XMLSchema1.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/XMLSchema1.xsd"
    xmlns:mstns="http://tempuri.org/XMLSchema1.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="TaxRates">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TaxYear" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="StartDate" minOccurs="1" maxOccurs="1" type="xs:date"/>
              <xs:element name="EndDate" minOccurs="1" maxOccurs="1" type="xs:date"/>
              <xs:element name="AdditionalRateMinIncome" minOccurs="1" maxOccurs="1" type="xs:int"/>
              <xs:element name="AdditionalRateTaxRate" minOccurs="1" maxOccurs="1" type="xs:float"/>
              <xs:element name="Bracket" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="LowerBound" minOccurs="1" maxOccurs="1" type="xs:int"/>
                    <xs:element name="UpperBound" minOccurs="1" maxOccurs="1" type="xs:int"/>
                    <xs:element name="Rate" minOccurs="1" maxOccurs="1" type="xs:float"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== samirichards/CM-Assistant/CM Assistant_UWP/CM Assistant_UWP/Data/TaxRates.xml
<?xml version="1.0" encoding="utf-8"?>
<TaxRates 
      xmlns="http://tempuri.org/XMLSchema1.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="BracketsSchema.xsd">
  <TaxYear>
    <StartDate>2000-04-01</StartDate>
    <EndDate>2001-03-30</EndDate>
    <AdditionalRateMinIncome>150001</AdditionalRateMinIncome>
    <AdditionalRateTaxRate>0.55</AdditionalRateTaxRate>
    <Bracket>
      <LowerBound>0</LowerBound>
      <UpperBound>12500</UpperBound>
      <Rate>1</Rate>
    </Bracket>
    <Bracket>
      <LowerBound>12501</LowerBound>
      <UpperBound>50000</UpperBound>
      <Rate>0.8</Rate>
    </Bracket>
    <Bracket>
      <LowerBound>50001</LowerBound>
      <UpperBound>150000</UpperBound>
      <Rate>0.6</Rate>
    </Bracket>
  </TaxYear>
</TaxRates>
